### PR TITLE
About Page

### PR DESCRIPTION
**Pull request by pAditya198**

### CODE REVIEW

**Comment by anujpuri72** [comment]
image

Inconsistent top padding and getting a  horizontal scroll in about section

**Comment by pAditya198** [comment]
> image
> 
> Inconsistent top padding and getting a horizontal scroll in about section

where did you get the horizontal scroll can you share

**Comment by pAditya198** [comment]
> image
> 
> Inconsistent top padding and getting a horizontal scroll in about section

got it. That is due to some other component
I'm taking full 100% width . Let me change it to 360

**Comment by anujpuri72** [comment]
And mono-rope font too is not being applied, it's getting set to default browser fallback font  in brave

**Comment by pAditya198** [comment]
Let me check on it's compatibility with brave

**Review by AmanRaj1608 — COMMENTED** [review]
Alignment and font issue on my device 
 
image

image

**Pull request merged**
